steps:
# Step 1: Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/abelunbound/com724', 'my-cloned-repo']

# Step 2: Change to the subdirectory and install dependencies
- name: 'python'
  dir: 'my-cloned-repo/gui_dash_backup'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt']

# Step 3: Deploy the application
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'my-cloned-repo/gui_dash_backup'
  args: ['app', 'deploy', '--quiet']

# Optionally, specify a timeout for the build
timeout: '1200s'
